commit_message: "\U00E696B0\U00E79A84\U00E7BFBB\U00E8ADAF\U00E68F90\U00E4BAA4\U00E4BE86\U00E887AA"
append_commit_message: false
files:
  - source: assets*
    translation: '%original_path%/zh_tw.%file_extension%'
