# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ S_1.16 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
       
      - uses: papeloto/action-zip@v1 #zipped file 1.15.2
        with:
          files: zh-TW/assets/
          dest: ResourcePack-Mod-zh_tw+Snapshot-1.16-V${{ github.run_number }}.zip
      - name: Upload 1.16 release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Snapshot-V${{ github.run_number }}
          file: ${{ github.workspace }}/ResourcePack-Mod-zh_tw+Snapshot-1.16-V${{ github.run_number }}.zip
          asset_name: ResourcePack-Mod-zh_tw+Snapshot-1.16-V${{ github.run_number }}.zip
          overwrite: true 
          body: "繁體中文化模組資源包(RPMTW) 版本:V${{ github.run_number }}發布囉!\n如何下載呢? 看到下方的Assets把選單打開，接著找到您要下載的版本點下去就可以下載囉!!!"
