name: CI

on:
  push:
    branches: [ S_1.16 ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
         npm i ${{ github.workspace }}/pack 
         node ${{ github.workspace }}/pack
         git config --global user.name 'github-actions[bot]'
          git config --global user.email 'actions@users.noreply.github.com'
          @"
          protocol=https
          host=github.com
          username=github-actions[bot]
          password=${{ secrets.GITHUB_TOKEN }}
          "@ > .\1.txt
          gc 1.txt|git credential-manager  store
          ri .\1.txt -Force
          git add .
          git commit -m "test"
          git push origin HEAD:${{ github.ref }}

      - name: Upload 1.16 release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: RPMTW-1.16-V${{ github.run_number }}
          file: ${{ github.workspace }}/pack/RPMTW-1.16.zip
          asset_name: RPMTW-1.16.zip
          overwrite: true 
          body: "繁體中文化模組資源包(RPMTW) 版本:V${{ github.run_number }} \n更新內容: [${{ github.event.head_commit.message }}](https://github.com/SiongSng/ResourcePack-Mod-zh_tw/commit/${{ github.sha }}) \n\n## 下載資訊\n1.16繁體中文化模組材質包 [點我下載](https://github.com/SiongSng/ResourcePack-Mod-zh_tw/releases/download/RPMTW-1.16-V${{ github.run_number }}/RPMTW-1.16.zip)"
