# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
    - "1.16"    
    - .github/workflows/*
  
  # workflow_dispatch:
   #似乎無用
   
 #  schedule:
  #  - cron:  '0 3 */14 * *' #似乎也沒有執行.....


jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: |
       cd ${{ github.workspace }}/Spider
       node .
  
    # - run: node ${{ github.workspace }}/Spider/index.js
    - name: Commit files
      run: |
        git config --global user.email "rrt467778@gmail.com.com"
        git config --global user.name "SiongSng"
        git add ./assets
        git commit -m "更新翻譯原始英文文本"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
